services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    command: python app/main.py
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./preprating
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    volumes:
      - ./preprating:/app
      - /app/node_modules
    environment:
      # в режиме разработки лучше включить поллинг для файловой системы
      - CHOKIDAR_USEPOLLING=true
      # указываем, куда мы будем обращаться за API (если нужно)
      #- REACT_APP_API_URL=http://localhost:${BACKEND_PORT}
    command: npm start
    depends_on:
      - backend
      - postgres_db

volumes:
  postgres_data: