"""add professor table

Revision ID: 8b7be2145a0d
Revises: 904ecb29690d
Create Date: 2025-04-19 22:33:41.659729

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8b7be2145a0d"
down_revision: Union[str, None] = "904ecb29690d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "professor",
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("academic_title", sa.String(length=100), nullable=True),
        sa.Column("faculty_id", sa.Integer(), nullable=False),
        sa.Column("bio", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["faculty_id"], ["faculty.id"], name=op.f("fk_professor_faculty_id_faculty")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_professor")),
    )
    op.create_table(
        "course_professor",
        sa.Column("subject_id", sa.Integer(), nullable=False),
        sa.Column("professor_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["professor_id"],
            ["professor.id"],
            name=op.f("fk_course_professor_professor_id_professor"),
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"], ["subject.id"], name=op.f("fk_course_professor_subject_id_subject")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_course_professor")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("course_professor")
    op.drop_table("professor")
    # ### end Alembic commands ###
