"""add program table

Revision ID: 20edf39edcb3
Revises: ec1fa002941b
Create Date: 2025-04-19 19:25:54.093620

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20edf39edcb3"
down_revision: Union[str, None] = "ec1fa002941b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "program",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "degree_level",
            sa.Enum("specialist", "bachelor", "master", "phd", name="program_level"),
            nullable=False,
        ),
        sa.Column("faculty_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["faculty_id"], ["faculty.id"], name=op.f("fk_program_faculty_id_faculty")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_program")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("program")
    # ### end Alembic commands ###
