"""course professor relation to review

Revision ID: b36c5fdc5ef9
Revises: 4ec49ded4654
Create Date: 2025-04-19 22:52:06.239240

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b36c5fdc5ef9"
down_revision: Union[str, None] = "4ec49ded4654"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("fk_review_course_professor_id_course_professor"),
        "review",
        "course_professor",
        ["course_professor_id"],
        ["id"],
    )
    op.drop_column("review", "created_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "review",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(
        op.f("fk_review_course_professor_id_course_professor"), "review", type_="foreignkey"
    )
    # ### end Alembic commands ###
