"""add subject table

Revision ID: 904ecb29690d
Revises: 20edf39edcb3
Create Date: 2025-04-19 22:23:54.864616

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "904ecb29690d"
down_revision: Union[str, None] = "20edf39edcb3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subject",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("program_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["program_id"], ["program.id"], name=op.f("fk_subject_program_id_program")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subject")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("subject")
    # ### end Alembic commands ###
