"""fix_review_entity_type_case

Revision ID: 912afd685ba2
Revises: da3d73349285
Create Date: 2025-04-20 09:56:31.937020

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "912afd685ba2"
down_revision: Union[str, None] = "da3d73349285"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_review_course_professor_id_course_professor", "review", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_review_course_professor_id_course_professor"),
        "review",
        "course_professor",
        ["course_professor_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_review_course_professor_id_course_professor"),
        "review",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_review_course_professor_id_course_professor",
        "review",
        "course_professor",
        ["course_professor_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
